<?php

declare(strict_types=1);

namespace Northrook\Debugger;

use Northrook\Helpers;

/** @var int[] $data */
?>
<h1>Warnings</h1>

<div class="tracy-inner">
  <table class="tracy-sortable">
      <?php foreach ( $data as $item => $count ) {
          [$file, $line, $message] = \explode( '|', $item, 3 ); ?>
        <tr>
          <td class="tracy-right"><?php echo $count ? "{$count}\xC3\x97" : ''; ?></td>
          <td>
            <pre><?php echo Helpers::escapeHtml( $message ), ' in ', Helpers::editorLink( $file, (int) $line ); ?></pre>
          </td>
        </tr>
      <?php } ?>
  </table>
</div>
