<?php

declare(strict_types=1);

namespace Northrook\Debugger;

use Northrook\Helpers;

/**
 * @var \Throwable    $ex
 * @var \Throwable[]  $exceptions
 * @var array[]       $actions
 * @var ExceptionView $this
 */
$title = $ex instanceof \ErrorException
        ? Helpers::errorTypeToString( $ex->getSeverity() )
        : \get_debug_type( $ex );
$code = $ex->getCode() ? ' #'.$ex->getCode() : '';

?>
<section class="tracy-section tracy-section--error">
    <?php if ( $ex->getMessage() ) { ?><p><?php echo Helpers::escapeHtml( $title.$code ); ?></p><?php } ?>


  <h1>
      <?php
      $title = $this->formatMessage( $ex ) ?: Helpers::escapeHtml( $title.$code );

echo "<span>{$title}</span>";

// foreach ( $actions as $item ) {
//     $link   = Helpers::escapeHtml( $item['link'] );
//     $target = empty( $item['external'] ) ? '' : ' target="_blank" rel="noreferrer noopener"';
//     $label  = Helpers::escapeHtml( $item['label'] );
//     echo "<a href=\"{$link}\"{$target} class=\"tracy-action\">{$label}&#x25ba;</a>";
// }
?>
  </h1>

    <?php if ( $ex->getPrevious() ) { ?>
      <div class="tracy-caused">
        <a href="#tracyCaused<?php echo \count( $exceptions ) + 1; ?>">Caused by <?php echo Helpers::escapeHtml(
            \get_debug_type( $ex->getPrevious() ),
        ); ?></a>
      </div>
    <?php } ?>
</section>
