<?php

declare(strict_types=1);

namespace Northrook\Debugger;

use Northrook\Dumper\Dumper;
use Northrook\Helpers;

/**
 * @var callable      $dump
 * @var bool          $showEnvironment
 * @var array         $obStatus
 * @var ExceptionView $this
 */
if ( ! $showEnvironment ) {
    return;
}

$constants = \get_defined_constants( true )['user'] ?? [];
?>
<section class="tracy-section">
  <h2 class="tracy-section-label"><a href="#" data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">Environment</a>
  </h2>

  <div class="tracy-section-panel tracy-collapsed">

    <div class="tracy-tabs">
      <ul class="tracy-tab-bar">
        <li class="tracy-tab-label tracy-active"><a href="#">$_SERVER</a></li>
          <?php if ( $_SESSION ?? null ) { ?>
            <li class="tracy-tab-label"><a href="#">$_SESSION</a></li>
          <?php } ?>
          <?php if ( $constants ) { ?>
            <li class="tracy-tab-label"><a href="#">Constants</a></li>
          <?php } ?>
        <li class="tracy-tab-label"><a href="#">Configuration</a></li>
          <?php if ( $obStatus ) { ?>
            <li class="tracy-tab-label"><a href="#">Output buffers</a></li>
          <?php } ?>

      </ul>


      <div>
        <div class="tracy-tab-panel tracy-pane tracy-active">
          <table class="tracy-sortable">
              <?php foreach ( $_SERVER as $k => $v ) { ?>
                <tr>
                  <th><?php echo Helpers::escapeHtml( $k ); ?></th>
                  <td><?php echo $dump( $v, $k ); ?></td>
                </tr>
              <?php } ?>
          </table>
        </div>


          <?php if ( $_SESSION ?? null ) { ?>
            <div class="tracy-tab-panel">
              <div class="tracy-pane">
                <table class="tracy-sortable">
                    <?php foreach ( $_SESSION as $k => $v ) { ?>
                      <tr>
                        <th><?php echo Helpers::escapeHtml( $k ); ?></th>
                        <td><?php echo '__NF' === $k ? '<i>Nette Session</i>' : $dump( $v, $k ); ?></td>
                      </tr>
                    <?php } ?>
                </table>
              </div>


                <?php if ( ! empty( $_SESSION['__NF']['DATA'] ) ) { ?>
                  <h3>Nette Session</h3>
                  <div class="tracy-pane">
                    <table class="tracy-sortable">
                        <?php foreach ( $_SESSION['__NF']['DATA'] as $k => $v ) { ?>
                          <tr>
                            <th><?php echo Helpers::escapeHtml( $k ); ?></th>
                            <td><?php echo $dump( $v, $k ); ?></td>
                          </tr>
                        <?php } ?>
                    </table>
                  </div>
                <?php } ?>
            </div>
          <?php } ?>



          <?php if ( $constants ) { ?>
            <div class="tracy-tab-panel tracy-pane">
              <table class="tracy-sortable">
                  <?php foreach ( $constants as $k => $v ) { ?>
                    <tr>
                      <th><?php echo Helpers::escapeHtml( $k ); ?></th>
                      <td><?php echo $dump( $v, $k ); ?></td>
                    </tr>
                  <?php } ?>
              </table>
            </div>
          <?php } ?>


        <div class="tracy-tab-panel">
            <?php $this->renderPhpInfo(); ?>

        </div>


          <?php if ( $obStatus ) { ?>
            <div class="tracy-tab-panel tracy-pane">
                <?php echo Dumper::toHtml( $obStatus, [Dumper::COLLAPSE_COUNT => 10] ); ?>
            </div>
          <?php } ?>
      </div>
    </div>
  </div>
</section>
