<?php

declare(strict_types=1);

namespace Northrook\Debugger;

use Northrook\Debugger;
use ErrorException;
use Throwable;

/**
 * @var Throwable     $ex
 * @var callable      $dump
 * @var ExceptionView $this
 */
$stack = $ex->getTrace();
// if (in_array($stack[0]['class'] ?? null, [DevelopmentStrategy::class, ProductionStrategy::class], true)) {
// 	array_shift($stack);
// }
if ( Debugger::class === ( $stack[0]['class'] ?? null ) && \in_array(
    $stack[0]['function'],
    ['shutdownHandler', 'errorHandler'],
    true,
) ) {
    \array_shift( $stack );
}

$expanded = null;
if (
    ( ! $ex instanceof ErrorException || \in_array(
        $ex->getSeverity(),
        [E_USER_NOTICE, E_USER_WARNING, E_USER_DEPRECATED],
        true,
    ) )
    && $this->isCollapsed( $ex->getFile() )
) {
    foreach ( $stack as $key => $row ) {
        if ( isset( $row['file'] ) && ! $this->isCollapsed( $row['file'] ) ) {
            $expanded = $key;

            break;
        }
    }
}

$file = $ex->getFile();
$line = $ex->getLine();

require __DIR__.'/section-stack-sourceFile.phtml';
require __DIR__.'/section-stack-callStack.phtml';
