<?php

declare(strict_types=1);

namespace Northrook\Debugger;

use Northrook\Helpers;

/**
 * @var \Throwable    $ex
 * @var \Throwable[]  $exceptions
 * @var array[]       $actions
 * @var ExceptionView $this
 */
$title = $ex instanceof \ErrorException
        ? Helpers::errorTypeToString( $ex->getSeverity() )
        : \get_debug_type( $ex );
$code = $ex->getCode() ? ' #'.$ex->getCode() : '';

?>
<section class="tracy-section tracy-section--error">
    <?php if ( $ex->getMessage() ) { ?><p><?php echo Helpers::escapeHtml( $title.$code ); ?></p><?php } ?>


  <h1><span><?php echo $this->formatMessage( $ex ) ?: Helpers::escapeHtml( $title.$code ); ?></span>
      <?php foreach ( $actions as $item ) { ?>
        <a href="<?php echo Helpers::escapeHtml(
            $item['link'],
        ); ?>" class="tracy-action"<?php echo empty( $item['external'] )
                        ? '' : ' target="_blank" rel="noreferrer noopener"'; ?>><?php echo Helpers::escapeHtml(
                            $item['label'],
                        ); ?>
          &#x25ba;</a>
      <?php } ?>
  </h1>

    <?php if ( $ex->getPrevious() ) { ?>
      <div class="tracy-caused">
        <a href="#tracyCaused<?php echo \count( $exceptions ) + 1; ?>">Caused by <?php echo Helpers::escapeHtml(
            \get_debug_type( $ex->getPrevious() ),
        ); ?></a>
      </div>
    <?php } ?>
</section>
