<?php

declare(strict_types=1);

namespace Northrook\Debugger;

use Northrook\{Debugger, Helpers};

/**
 * @var string $file
 * @var int    $line
 * @var int    $expanded
 */
$sourceOriginal = $file && @\is_file( $file ) ? [$file, $line] : null; // @ - may trigger error
$sourceMapped   = $sourceOriginal ? Debugger::mapSource( $file, $line ) : null;
?>

<section class="tracy-section">
  <h2 class="tracy-section-label"><a href="#" data-tracy-ref="^+" class="tracy-toggle<?php echo ( $collapsed
              = null !== $expanded ) ? ' tracy-collapsed' : ''; ?>">Source file</a></h2>

  <div class="tracy-section-panel<?php echo $collapsed ? ' tracy-collapsed' : ''; ?>">
      <?php if ( $sourceOriginal && $sourceMapped ) { ?>
        <div class="tracy-tabs">
          <ul class="tracy-tab-bar">
            <li class="tracy-tab-label<?php echo $sourceMapped['active'] ? '' : ' tracy-active'; ?>">
              <a href="#">PHP</a></li>
            <li class="tracy-tab-label<?php echo $sourceMapped['active'] ? ' tracy-active' : ''; ?>">
              <a href="#"><?php echo Helpers::escapeHtml( $sourceMapped['label'] ); ?></a></li>
          </ul>

          <div>
            <div class="tracy-tab-panel<?php echo $sourceMapped['active'] ? '' : ' tracy-active'; ?>">
              <p><b>File:</b> <?php echo Helpers::editorLink( ...$sourceOriginal ); ?></p>
                <?php echo ExceptionView::highlightFile( ...$sourceOriginal ); ?>
            </div>

            <div class="tracy-tab-panel<?php echo $sourceMapped['active'] ? ' tracy-active' : ''; ?>">
              <p><b>File:</b> <?php echo Helpers::editorLink( $sourceMapped['file'], $sourceMapped['line'] ); ?></p>
                <?php echo ExceptionView::highlightFile(
                    $sourceMapped['file'],
                    $sourceMapped['line'],
                    php : false,
                ); ?>
            </div>
          </div>
        </div>
      <?php }
      else { ?>
        <div class="title"><b>File:</b> <?php echo Helpers::editorLink( $file, $line ); ?></div>
          <?php if ( $sourceOriginal ) {
              echo ExceptionView::highlightFile( ...$sourceOriginal );
          } ?>
      <?php } ?>

  </div>
</section>
