<?php

declare(strict_types=1);

namespace Northrook\Debugger;

use Northrook\Dumper\Dumper;

/**
 * @var string      $type
 * @var \stdClass[] $panels
 */
$icons = <<<'EOD'

    	<div class="tracy-icons">
    		<a href="#" data-tracy-action="window" title="open in window">&curren;</a>
    		<a href="#" data-tracy-action="close" title="close window">&times;</a>
    	</div>

    EOD;

echo '<div itemscope>';

foreach ( $panels as $panel ) {
    $content = $panel->panel ? ( $panel->panel."\n".$icons ) : '';
    $class   = 'tracy-panel '.( 'ajax' === $type ? '' : 'tracy-panel-persist' ).' tracy-panel-'.$type; ?>
<div class="<?php echo $class; ?>" id="tracy-debug-panel-<?php echo $panel->id; ?>" data-tracy-content='<?php echo \str_replace(
    ['&', "'"],
    [
        '&amp;',
        '&#039;',
    ],
    $content,
); ?>'></div><?php
}

echo '<meta itemprop=tracy-snapshot content=', Dumper::formatSnapshotAttribute( Dumper::$liveSnapshot ), '>';
echo '</div>';
